<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>

<div class="search-inner">

    <a href="#"></a>

    <form class="search-form" id="search_mini_form" action="<?= $block->escapeUrl($helper->getResultUrl()) ?>" method="get">
          
        <input id="search"
            data-mage-init='{"quickSearch":{
                "formSelector":"#search_mini_form",
                "url":"<?= $block->escapeUrl($helper->getSuggestUrl())?>",
                "destinationSelector":"#search_autocomplete",
                "minSearchLength":"<?= $block->escapeHtml($helper->getMinQueryLength()) ?>"}
            }'
            type="text"
            name="<?= $block->escapeHtmlAttr($helper->getQueryParamName()) ?>"
            value="<?= $block->escapeHtmlAttr($helper->getEscapedQueryText()) ?>"
            placeholder="<?= $block->escapeHtmlAttr(__('Search')) ?>"
            class="input-text"
            maxlength="<?= $block->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
            role="combobox"
            aria-haspopup="false"
            aria-autocomplete="both"
            autocomplete="off"
            aria-expanded="false"/>
            <div id="search_autocomplete" class="search-autocomplete"></div>
            <?= $block->getChildHtml() ?>

        <button type="submit" title="<?= $block->escapeHtmlAttr(__('Search')) ?>" class="action search" aria-label="Search">
            <svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 54 37.99"><path d="M70.56,61.22l-14-17A2,2,0,0,0,53.73,44a2.09,2.09,0,0,0-.26,2.83L64.75,60.5H19a2,2,0,0,0,0,4H64.75L53.47,78.22a2.1,2.1,0,0,0,.26,2.83,2,2,0,0,0,2.83-.27l14-17A2.08,2.08,0,0,0,70.56,61.22Z" transform="translate(-17 -43.5)"/></svg>
        </button>
        
    </form>

</div>