<div class="here-to-help has-animation">

  <div class="help-title">Our sales team are here to help</div>

  <p>With expert knowledge and a wide network of suppliers, we'll find you the best product for the job - all at competitive prices.</p>

  <p><strong>Call now on <a href="tel:0441772956270">+44(0) 1772 956 270</a> or, email us at <a href="mailto:sales@cuttingedgeservices.co.uk">sales@cuttingedgeservices.co.uk</a> and we'll do the rest</strong></p>

</div>
