<div class="detail-item">
    <div class="detail-title">Delivery &amp; Returns<span class="icon-plus"></span></div>
    <div class="detail-content" style="display:none;">
      <p>We offer free next day delivery for UK orders of £100 or more. For orders of less than £100, next day delivery is charged at £4.95.
      Delivery is the next working day, if placed before 3pm. Any orders placed after 3pm will be dispatched the following business day and sent on next day delivery.</p>

      <p>Delivery is 5 days a week Monday – Friday (excluding bank holidays).</p>

      <p>Deliveries to BT, GY, HS1, IM, IV41, JE, KA27, PA20, PA41, PA60, PH42, TR21, ZE1 and EIRE are charged at £8.50 for parcels < 200g and £63.50 for parcels > 200g.
      Delivery timescales are based on location and can vary depending on the items being ordered, although we endeavour to run a 3-5 day service for these areas.</p>

      <p>You may return your order any time up to 14 days after the day of receipt of goods. In this event, you must notify us by contacting
      Customer Services on +44 (0) 1772 458400 (Ext. 2000) between 8am and 5.30pm, Monday to Friday.</p>

      <p>The goods must be returned to us in their original condition, with any seals and shrink-wrap intact.</p>

      <p>For full delivery and returns information please see our delivery & returns pages.</p>
    </div>
</div>
