<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Address\Grid $block */
$customerAddressView = $block->getData('customer_address');
?>

<div class="block block-addresses-list">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Additional Address Entries')) ?></strong></div>
    <div class="block-content">
        <?php if ($_pAddsses = $block->getAdditionalAddresses()) : ?>

            <div class="table-wrapper additional-addresses">
                <table class="data table table-additional-addresses-items history" id="additional-addresses-table">
                    <caption class="table-caption"><?= $block->escapeHtml(__('Additional addresses')) ?></caption>
                    <thead>
                    <tr>
                        <th scope="col" class="name"><?= $block->escapeHtml(__('Name')) ?></th>
                        <th scope="col" class="streetaddress"><?= $block->escapeHtml(__('Address')) ?></th>
                        <th scope="col" class="city"><?= $block->escapeHtml(__('City')) ?></th>
                        <th scope="col" class="country"><?= $block->escapeHtml(__('Country')) ?></th>
                        <th scope="col" class="zip"><?= $block->escapeHtml(__('PostCode')) ?></th>
                        <th scope="col" class="phone"><?= $block->escapeHtml(__('Phone')) ?></th>
                        <th scope="col" class="actions"> </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($_pAddsses as $address) : ?>
                        <tr>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Name')) ?>" class="name"><?= $block->escapeHtml($address->getFirstname()) ?> <?= $block->escapeHtml($address->getLastname()) ?></td>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Address')) ?>" class="streetaddress"><?= $block->escapeHtml($block->getStreetAddress($address)) ?></td>
                            <td data-th="<?= $block->escapeHtmlAttr(__('City')) ?>" class="city"><?= $block->escapeHtml($address->getCity()) ?></td>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Country')) ?>" class="country"><?= $block->escapeHtml($block->getCountryByCode($address->getCountryId())) ?></td>
                            <td data-th="<?= $block->escapeHtmlAttr(__('PostCode')) ?>" class="zip"><?= $block->escapeHtml($address->getPostcode()) ?></td>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Phone')) ?>" class="phone"><?= $block->escapeHtml($address->getTelephone()) ?></td>
                            <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="actions">
                                <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/address/edit', ['id' => $address->getId()])) ?>"><span><?= $block->escapeHtml(__('Edit')) ?></span></a>
                                <a class="action delete" href="#" role="delete-address" data-address="<?= $block->escapeHtmlAttr($address->getId()) ?>"><span><?= $block->escapeHtml(__('Delete')) ?></span></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <?php if ($block->getChildHtml('pager')) : ?>
                <div class="customer-addresses-toolbar toolbar bottom"><?= $block->getChildHtml('pager') ?></div>
            <?php endif ?>
        <?php else : ?>
            <p class="empty"><?= $block->escapeHtml(__('You have no other address entries in your address book.')) ?></p>
        <?php endif ?>
    </div>
</div>

<div class="actions-toolbar">
    <div class="primary">
        <button type="button" role="add-address" title="<?= $block->escapeHtmlAttr(__('Add New Address')) ?>" class="action primary add"><span><?= $block->escapeHtml(__('Add New Address')) ?></span></button>
    </div>
    <div class="secondary">
        <a class="action back" href="<?= $block->escapeUrl($block->getUrl('customer/account')) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".page-main": {
            "address": {
                "deleteAddress": "td a[role='delete-address']",
                "deleteUrlPrefix": "<?= $block->escapeJs($block->escapeUrl($block->getDeleteUrl())) ?>id/",
                "addAddress": "button[role='add-address']",
                "addAddressLocation": "<?= $block->escapeJs($block->escapeUrl($block->getAddAddressUrl())) ?>"
            }
        }
    }
</script>
