<address>
    Cutting Edge Services Ltd<br>
    Matrix Park, Western Avenue<br>
    Buckshaw Village, Chorley<br>
    Lancashire, PR7 7NB
</address>
<ul class="socials">
    <li><a href="https://www.facebook.com/cuttingedgeservicesltd" target="_blank"><img class="social-grey" src="<?php echo $this->getViewFileUrl('images/footer/facebook.svg'); ?>"><img class="social-red" src="<?php echo $this->getViewFileUrl('images/footer/facebook-hover.svg'); ?>"></a></li>
    <li><a href="https://twitter.com/CES_cuttingedge" target="_blank"><img class="social-grey" src="<?php echo $this->getViewFileUrl('images/footer/twitter.svg'); ?>"><img class="social-red" src="<?php echo $this->getViewFileUrl('images/footer/twitter-hover.svg'); ?>"></a></li>
    <li><a href="https://www.linkedin.com/company/ces-cutting-edge-services-ltd/" target="_blank"><img class="social-grey" src="<?php echo $this->getViewFileUrl('images/footer/linkedin.svg'); ?>"><img class="social-red" src="<?php echo $this->getViewFileUrl('images/footer/linkedin-hover.svg'); ?>"></a></li>
    <li><a href="https://www.youtube.com/channel/UC80UovkJ_SKx4oboglTQq1A" target="_blank"><img class="social-grey" src="<?php echo $this->getViewFileUrl('images/footer/youtube.svg'); ?>"><img class="social-red" src="<?php echo $this->getViewFileUrl('images/footer/youtube-hover.svg'); ?>"></a></li>
</ul>