<?php
/**
 * @category FishPig
 * @package FishPig_WordPress
 * @notes This template is used when there post/list.phtml doesn't have a child block called 'renderer'
 * @notes This happens when post/list.phtml is called in via PHP rather than via the default layout handles
 */
?>
<?php if ($post = $this->getPost()): ?>
	<div class="post-list-item">

		<div class="post-entry">
			<?php if ($image = $post->getImage()): ?>
        <?php $imageUrl = $image->getResizer() ? $image->getResizer()->constrainOnly(true)->keepFrame(false)->keepAspectRatio(true)->resize(600, null) : '' ?>
				<div class="post-image">
					<a href="<?php echo $post->getUrl() ?>" title="<?php echo $this->escapeHtml($post->getName()) ?>"><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($post->getName()) ?>"/></a>
				</div>
			<?php endif; ?>

      <p><?php echo $post->getPostDate('') ?></p>

      <h2>
  			<a href="<?php echo $post->getUrl() ?>" title="<?php echo $this->escapeHtml($post->getName()) ?>">
  				<?php echo $this->escapeHtml($post->getName()) ?>
  			</a>
  		</h2>

			<div class="post-excerpt"><?php echo $post->getExcerpt(25) ?></div>
		</div>

	</div>
<?php endif; ?>
