<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$titleHtml = '';
if (trim($block->getPageHeading())) {
    $titleHtml = '<span class="base" data-ui-id="page-title-wrapper" '
        . $block->getAddBaseAttribute()
        . '>'
        . $block->escapeHtml($block->getPageHeading())
        . '</span>';
}
?>
<?php if ($titleHtml) : ?>
<div class="page-title-wrapper<?= $block->escapeHtmlAttr($cssClass) ?>">
  <div class="title-inner">
    <h1 class="page-title"
        <?php if ($block->getId()) : ?> id="<?= $block->escapeHtmlAttr($block->getId()) ?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()) : ?>
            aria-labelledby="<?= $block->escapeHtmlAttr($block->getAddBaseAttributeAria()) ?>"
        <?php endif; ?>>
        <?= /* @noEscape */ $titleHtml ?>
    </h1>
    <?= $block->getChildHtml() ?>
  </div>

  <div class="product-brand">
  <?php
    $attributeHelper = $block->getLayout()->createBlock('TwentyOneDigital\HelperModule\Block\AttributeHelper');
    $categoryHelper = $block->getLayout()->createBlock('TwentyOneDigital\HelperModule\Block\CategoryHelper');
    $productHelper = $block->getLayout()->createBlock('TwentyOneDigital\HelperModule\Block\ProductHelper');
    $manufacturer = $attributeHelper->getAttribute('manufacturer');
    $brand = $attributeHelper->getAttribute('brand');
  ?>
  <?php
      $product = $attributeHelper->getProduct();
      $brandCategories = $categoryHelper->getCategories(293);
      foreach($brandCategories as $brandCategory){
          $isInCategory = $productHelper->isInCategory($product->getId(), $brandCategory['id']);

          $brandName = isset($brand) ? $brand : $manufacturer;
          if($isInCategory && $brandCategory['name'] == $brandName) {
              $brandImage = $categoryHelper->getCategoryAttribute($brandCategory['id'], "magepow_thumbnail");
              if($brandImage){
                  ?><img src="<?= $attributeHelper->getBaseUrl() ?><?= strstr($brandImage, 'pub') ?>"/><?php
              }
          }
      }
  ?>
  </div>

</div>
<?php endif; ?>
