<section id="account-cta">
    <picture>
        <source srcset="<?= $block->getViewFileUrl('images/account-banner-desktop.avif') ?>" media="(min-width:768px)" />
        <source srcset="<?= $block->getViewFileUrl('images/account-banner-mobile.avif') ?>" media="(max-width:767px)" />
        <img src="<?= $block->getViewFileUrl('images/account-banner-desktop.avif') ?>" loading="lazy"/>
    </picture>
    <main>
        <h3>OUR SALES TEAM IS HERE TO HELP</h3>
        <p>Trouble logging in? Concerns with your order?</p>
        <p><strong>Call now on <a href="tel:+441772956270">+44(0) 1772 956 270</a> or email us at <a href="mailto:sales@cuttingedgeservices.co.uk">sales@cuttingedgeservices.co.uk</a> and we'll do the rest.</strong></p>
    </main>
</section>