<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
$cur = new NumberFormatter('en_GB', NumberFormatter::CURRENCY);

/* get the tax helper */

$_taxHelper = $this->helper('Magento\Catalog\Helper\Data');

?>
<?php if ($block->hasSpecialPrice()) : ?>
    <span class="special-price">
        <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Special Price'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>
    <span class="old-price">
        <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
        <span class="price-wrapper price-excluding-tax" data-label="EX VAT">

            <span class="price">
               <?= $cur->formatCurrency($priceModel->getAmount()->getBaseAmount(),'GBP') ?>
            </span>
        </span>

        <?php
        $prod = $block->getSaleableItem();
        $regPriceExclTax = $prod->getPriceInfo()->getPrice('regular_price')->getValue();
        $finalPriceExclTax = $prod->getPriceInfo()->getPrice('final_price')->getValue();
        $regPriceIncTax = $_taxHelper->getTaxPrice($prod,$prod->getPriceInfo()->getPrice('regular_price')->getValue(),true);
        $finalPriceIncTax = $_taxHelper->getTaxPrice($prod,$prod->getPriceInfo()->getPrice('final_price')->getValue(),true);
        if ($regPriceExclTax > $finalPriceExclTax):
            $diffExTax = $regPriceExclTax - $finalPriceExclTax;
            $diffIncTax = $regPriceIncTax - $finalPriceIncTax;
        ?>
    </span>
    <span class="saving price-excluding-tax">
        <span>Save</span><span><?= $cur->formatCurrency($diffExTax,'GBP') ?></span>
    </span>
    <span class="saving price-including-tax">
        <span>Save</span><span><?= $cur->formatCurrency($diffIncTax,'GBP') ?></span>

    </span>
    <?php 
    endif;

?>

<?php else : ?>
    <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
<?php endif; ?>

<?php if ($block->showMinimalPrice()) : ?>
    <?php if ($block->getUseLinkForAsLowAs()) : ?>
        <a href="<?= $escaper->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </a>
    <?php else : ?>
        <span class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif ?>
<?php endif; ?>